##tomcat端口及虚拟路径的配置
server:
  port: 8080
  servlet:
    context-path: /crmproject

#静态资源
spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crmproject?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 159258
mybatis:
  mapper-locations: /mapper/**.xml
  type-aliases-package: com.csdj.crmproject.crmproject.entity